.gitignore, server.js
Update filename to remove error when running the server.
=> fix filename error

app/api/core/streams/StreamPost.js, app/api/core/streams/StreamPut.js, models/DataStream.js, server.js
=> Improving stream put post

.dockerignore, .gitignore, Dockerfile, app/ws/RadioTower.js, config.js, docker-compose.yml, package-lock.json, package.json, server.js
- changes to docker configuration
- removed init response - breaks compatibility with old clients
=> Kinda goes on to v004

readme.md
- added payload size limits as discussed on Speckle Slack
- adjusted formatting for a few things whilst i'm here :)
- added link to license file
=> add payload size limits & formatting

readme.md
added logo same as viewer repo
#vanityPR
=> prettify docs

readme.md
Hi, these are Debian install instructions for the readme. If you prefer a "short" version like the Heroku instructions above, tell me and I'll amend.
Cheers
Yorik
=> Added Debian install instructions

package-lock.json, package.json, server.js
speckle admin and speckle viewer are now published on npm under the `@speckle` org.
=> moved speckle plugins to org, updated dependecies

app/ws/RadioTower.js, docker-compose.yml
=> Hotifx ws messagesending

.env-base, app/api/v1/accounts/UserProfile.js, app/api/v1/accounts/UserSearch.js, docker-compose.yml, server.js
These changes address the first two parts of the solution to #92.
=> Fix bugs enabling email exfiltration

.eslintrc.js, app/api/v1/accounts/UserCreate.js, app/api/v1/clients/ClientGet.js, app/api/v1/clients/ClientPut.js, app/api/v1/comments/CommentDelete.js, app/api/v1/index.js, app/api/v1/middleware/BulkObjectSave.js, app/api/v1/middleware/GetResourceByType.js, app/api/v1/objects/ObjectDelete.js, app/api/v1/objects/ObjectGet.js, app/api/v1/streams/StreamDiff.js, app/api/v1/streams/StreamObjectsGet.js, app/ws/ClientStore.js, app/ws/middleware/VerifyClient.js, config/passport.js, models/Comment.js, models/DataStream.js, models/SpeckleDataTypesEnum.js, models/User.js, models/UserAppClient.js, server.js
=> adding some extra rules, to flex out eslint

.eslintrc.js, app/api/comments/CommentGetAll.js, app/api/index.js, app/api/middleware/ProtectedFields.js, app/api/projects/ProjectDelete.js, app/api/projects/ProjectDeleteStream.js, app/api/projects/ProjectDeleteUser.js, app/api/projects/ProjectGetAll.js, app/api/projects/ProjectPut.js, app/api/projects/ProjectPutAddStream.js, app/api/projects/ProjectPutAddUser.js, app/api/projects/ProjectPutDowngradeUser.js, app/api/projects/ProjectPutUpgradeUser.js, app/api/streams/StreamDelete.js, app/api/streams/StreamDuplicate.js, models/DataStream.js, models/Project.js, plugins.js, server.js
=> Adds permission handling routes for projects

app/api/clients/ClientDelete.js, app/api/clients/ClientGet.js, app/api/clients/ClientPut.js
=> moves resource permission checks on client edit routes to corresponding stream

package-lock.json
no 🚨 🚨 🚨 on `npm install` plz: https://www.npmjs.com/advisories/788
=> update yaml-js dev dependency to make npm audit happy

readme.md
adds link to discourse setup thread and closes #126 - thanks to @arendvw!
=> add discourse setup thread

app/api/index.js
=> comments reference to UserVerify

.npmrc, package-lock.json, package.json, releaserc.json
=> build(npm): set up npm deployment

package-lock.json, package.json
Sorry for the hacky set up but this was the easiest way around this issue. Should all be clean
commits from now on!
=> fix(semantic-release): add a dummy commit to trigger semantic-release

.releaserc.json
forgot the . in front of releaserc.json... my bad.
Last one and we're good!
=> fix(semantic-release): use .releaserc.json to control release mechanism

app/ws/RadioTower.js
Small fix to what was causing the server to break when broadcasting messages to a room.
On the topic of Websockets. Is there anywhere I can find:
1. What message payload is expected to look like? There is a chance my fix is pointless is I just missed a crucial variable
2. What the routine of connecting/disconnecting is? I notice that you can `join` and `leave` rooms but am not sure what those are for.
3. Is it normal that I get disconnected after about a minute? it seems `ws.on('close')` event happens for some reason and I get bumped off the server.
=> Websockets fix

.env-base, app/api/index.js
- adds a env var for jn number masks
- fixes version number (tries to get it from the current git tag)
=> fix(version): correctly displays version from git tag if possible

app/api/middleware/PermissionCheck.js, app/api/projects/ProjectPut.js, app/api/projects/ProjectPutAddStream.js, app/api/streams/StreamPut.js
=> Hotfix perm nulls

app/api/objects/ObjectDerive.js, app/api/streams/StreamDelete.js, app/api/streams/StreamGetAll.js, package.json, test/api/object.test.js, test/api/streams.test.js
And a new batch of test for y'all! Includes a couple of fixes too streams and 1 broken test for objects.
Not that I'm bragging or anything but **cough** 166 tests **cough**...
=> Stream and Object tests

.gitignore, app/ws/SpeckleSockets.js, package-lock.json, package.json, test/api/accounts.test.js, test/api/client.test.js, test/api/object.test.js, test/api/project.test.js, test/api/streams.test.js, test/testUtils.js, test/ws/ws.test.js
As promised. Some tests for websocket functions. Not super complete but gets the ball rolling.
=> Websocket Tests

app/api/streams/StreamApplyDelta.js
changes according to https://github.com/speckleworks/SpeckleServer/commit/accd881d00379467bc80f65f7fc7e2890424ba5c
=> changes according to StreamGetDelta.js

app/api/streams/StreamApplyDelta.js
flattens the layer structure of the "delted" stream: only one layer remains, containing all the stream's objects.
=> flattens the layer structure of the "delted" stream
